# Generated by Django 6.0.3 on 2026-07-27 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


def gen_unique_idempotency_keys(apps, schema_editor):
    MaterialRequest = apps.get_model('api', 'MaterialRequest')
    for req in MaterialRequest.objects.all():
        if not req.idempotency_key:
            req.idempotency_key = uuid.uuid4()
            req.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_materialrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Webhook Event',
                'verbose_name_plural': 'Processed Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(gen_unique_idempotency_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='materialrequest',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OutboundSyncDeadLetterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('attempt_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter_logs', to='api.materialrequest')),
            ],
            options={
                'verbose_name': 'Outbound Sync Dead Letter Log',
                'verbose_name_plural': 'Outbound Sync Dead Letter Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]

