"""
Django settings for stockpad_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import urllib.parse
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_dotenv():
    """Load backend/.env for local runs; production platforms inject vars directly."""
    env_file = BASE_DIR / ".env"
    if not env_file.exists():
        return
    for raw_line in env_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if key:
            os.environ.setdefault(key, value)


def _env(name, default=None):
    """Read an environment variable, stripping accidental leading/trailing whitespace."""
    value = os.environ.get(name)
    if value is None:
        return default
    value = value.strip()
    return value if value else default


_load_local_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (_env("DJANGO_DEBUG", "True") or "True").lower() not in ("false", "0", "no")

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = _env("DJANGO_SECRET_KEY")
if not _secret_key_env:
    if DEBUG:
        # Insecure fallback — ONLY acceptable for local development
        _secret_key_env = "django-insecure-6fqhjcz1*=p24m2ux(7z_dy=_u*m-rz(qrw41bw4q&+aim*5be"
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable must be set in production.")
SECRET_KEY = _secret_key_env

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stockpad_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "stockpad_backend.wsgi.application"


def _parse_database_url(database_url):
    url = urllib.parse.urlparse(database_url.strip())
    if url.scheme not in ("postgres", "postgresql"):
        raise ImproperlyConfigured(
            f"DATABASE_URL must use postgres/postgresql scheme, got {url.scheme!r}."
        )

    query = urllib.parse.parse_qs(url.query)
    sslmode = (query.get("sslmode") or ["require"])[0]

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": urllib.parse.unquote(url.path.lstrip("/")),
        "USER": urllib.parse.unquote(url.username or ""),
        "PASSWORD": urllib.parse.unquote(url.password or ""),
        "HOST": url.hostname or "localhost",
        "PORT": str(url.port or "5432"),
        "CONN_MAX_AGE": 60,
        "OPTIONS": {"sslmode": sslmode},
    }


db_url = _env("DATABASE_URL")
if db_url:
    try:
        db_config = _parse_database_url(db_url)
    except ImproperlyConfigured:
        raise
    except Exception as exc:
        raise ImproperlyConfigured(f"Invalid DATABASE_URL: {exc}") from exc
else:
    db_name = _env("DB_NAME", "stockpad_db")
    db_user = _env("DB_USER", "postgres")
    db_password = _env("DB_PASSWORD")
    db_host = _env("DB_HOST", "localhost")
    db_port = _env("DB_PORT", "5432")

    if not db_password:
        if DEBUG:
            db_password = "postgres"
        else:
            raise ImproperlyConfigured(
                "DB_PASSWORD or DATABASE_URL environment variable is missing for production."
            )

    db_config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": db_host,
        "PORT": db_port,
        "CONN_MAX_AGE": 60,
    }
    if db_host not in ("localhost", "127.0.0.1"):
        db_config["OPTIONS"] = {"sslmode": "require"}

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db_test.sqlite3",
        }
    }
else:
    DATABASES = {"default": db_config}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL
AUTH_USER_MODEL = "api.User"

# REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Simple JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'api.authentication_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', 'stockpad.eg@gmail.com')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD', '')  # set via environment variable
DEFAULT_FROM_EMAIL = _env('EMAIL_HOST_USER', 'stockpad.eg@gmail.com')

# Google OAuth Credentials
GOOGLE_CLIENT_ID = _env('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = _env('GOOGLE_CLIENT_SECRET', '')


# ── Website 1 (WM Website) Integration Settings ──────────────────────────────
PE_BACKEND_PUBLIC_URL = (
    _env("PE_BACKEND_PUBLIC_URL")
    or "https://stockpad-web-2-production.up.railway.app"
).rstrip("/")

# Primary env var names (task spec / new standard):
WM_WEBSITE_BASE_URL = (
    _env("WM_WEBSITE_BASE_URL")
    or _env("SITE_A_BASE_URL")
    or "https://stockpad-backend-production.up.railway.app"
).rstrip("/")
WM_WEBSITE_API_KEY = (
    _env("WM_WEBSITE_API_KEY")
    or _env("SITE_A_API_KEY")
)  # sent as X-Site-B-API-Key on all outbound calls to WM Website
WEBHOOK_SHARED_SECRET = (
    _env("WEBHOOK_SHARED_SECRET")
    or _env("SITE_A_WEBHOOK_SECRET")
)  # HMAC-SHA256 shared secret — used to verify X-Webhook-Signature on inbound webhooks
_site_b_webhook = _env("SITE_B_PUBLIC_WEBHOOK_URL")
if _site_b_webhook:
    _site_b_webhook = _site_b_webhook.rstrip("/")
    if not _site_b_webhook.endswith("/api/webhooks/material-status"):
        if _site_b_webhook.endswith("/api/webhooks/material-status/"):
            pass
        else:
            _site_b_webhook = f"{_site_b_webhook}/api/webhooks/material-status"
SITE_B_PUBLIC_WEBHOOK_URL = (
    _site_b_webhook or f"{PE_BACKEND_PUBLIC_URL}/api/webhooks/material-status/"
)

# Backward-compat aliases — existing .env files using SITE_A_* continue to work
SITE_A_BASE_URL       = WM_WEBSITE_BASE_URL
SITE_A_API_KEY        = WM_WEBSITE_API_KEY
SITE_A_WEBHOOK_SECRET = WEBHOOK_SHARED_SECRET

# Startup validation check for production settings
if not DEBUG:
    missing_vars = []
    if not WM_WEBSITE_API_KEY:
        missing_vars.append("WM_WEBSITE_API_KEY (or SITE_A_API_KEY)")
    if not WEBHOOK_SHARED_SECRET:
        missing_vars.append("WEBHOOK_SHARED_SECRET (or SITE_A_WEBHOOK_SECRET)")
    if not SITE_B_PUBLIC_WEBHOOK_URL:
        missing_vars.append("SITE_B_PUBLIC_WEBHOOK_URL")

    if missing_vars:
        raise ImproperlyConfigured(
            f"Production integration settings missing: {', '.join(missing_vars)}. "
            "Please configure these environment variables."
        )
